"""checking for updates

Revision ID: 9a642b32735c
Revises: ec9bf9181c97
Create Date: 2023-05-29 16:11:51.291926

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a642b32735c'
down_revision = 'ec9bf9181c97'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
